# Offense count: 126
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 150

Metrics/BlockLength:
  CountComments: false  # count full line comments?

Metrics/ClassLength:
  CountComments: false  # count full line comments?