Metrics/LineLength:
  Max: 150

Metrics/BlockLength:
  CountComments: false

Metrics/ClassLength:
  CountComments: false

Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Layout/IndentationConsistency:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false