development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://uhryqunlsrpfxe:jJPeLMP3I7hi5ZEz-awxIOsF3N@ec2-54-225-64-254.compute-1.amazonaws.com:5432/dd4nieijciotkf
